name: Test Automation Workflow

on:
  schedule:
  - cron: 30 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -DisHeadless=true
      
    - name: Upload Test logs Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Test logs
        path : logs/
        
    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: screenshots
        path : screenshots/
        
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Test Reports
        path : report.html
        
    - name: Test Execution Status
      run: echo "Test Execution Completed"

    - name: Copy Report to github pages folder
      if: always()
      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAT1234 }}
        clean: true


